name: Fix Sub Ouput
    
on:
    push:
        paths:
            - 'python/replace.py'

#    workflow_dispatch:
    schedule:
        - cron: '0 */6 * * *'
jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch content from URL and update file
        run: |
          # 从一个由环境变量 secrets.INPUT_URL 指定的 URL 下载内容，然后使用 base64 解码，
          # 并将解码后的内容保存到当前目录下的 ./sub 文件中。
          curl -L "${{ secrets.INPUT_URL }}" | base64 --decode > ./sub

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - name: Run Replace
        run: |
            python python/replace.py

      - name: Commit Sub
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git diff --quiet && get diff -staged --quiet || git commit -m "Fix Sub"
          git push
      
      - name: Run Pretest
        run: |
            python python/pretest.py
            
      - name: Convert Sub to Base64
        run: |
          content=$(cat sub | base64 | tr -d '\n')
            echo "$content" > sub64

      - name: Convert Pretest to Base64
        run: |
          content=$(cat python/pretest | base64 | tr -d '\n')
            echo "$content" > python/pretest64

      - name: Commit Base64 Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git diff --quiet && get diff -staged --quiet || git commit -m "Convert to Base64"
          git push
 
